version: '3.1'
services:
  web:
    image: odoo:18
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8072:8072"
    stdin_open: true
    tty: true
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - ODOO_ADDONS_PATH=/usr/lib/python3/dist-packages/odoo/addons,/mnt/custom_addons
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/custom_addons
  db:
    image: postgres:16.2
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
volumes:
  odoo-web-data:
  odoo-db-data:
